# Generated by Django 2.1.7 on 2019-04-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nome de família')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('birthdate', models.DateField()),
                ('law_firm_name', models.CharField(blank=True, max_length=100, verbose_name='Escritório')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff - status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Usuário ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de inscrição')),
                ('is_trusty', models.BooleanField(default=False, help_text='Designates whether this user has confirmed his account.', verbose_name='E-mail foi confirmado?')),
                ('codigo_adesao', models.CharField(blank=True, max_length=32, verbose_name='Código da adesão')),
                ('situacao_adesao', models.CharField(blank=True, max_length=32, verbose_name='Situação da adesão')),
                ('telefone_contato', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone para contato')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.CharField(auto_created=True, blank=True, max_length=13, primary_key=True, serialize=False, unique=True)),
                ('law_firm', models.CharField(max_length=120, verbose_name='Nome do escritório')),
                ('law_firm_branch', models.CharField(max_length=100, verbose_name='Unidade do escritório')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_status', models.BooleanField(blank=True)),
                ('status_assinatura', models.BooleanField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=7)),
                ('preco', models.FloatField(blank=True)),
                ('periodo', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='plangroup',
            name='plan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Planos'),
        ),
        migrations.AddField(
            model_name='plangroup',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='group_law_firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.LawFirm'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
