# Generated by Django 2.1.7 on 2019-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190422_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_law_firm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='law_firm_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Sobrenome'),
        ),
        migrations.DeleteModel(
            name='LawFirm',
        ),
    ]
