# Generated by Django 2.1.7 on 2019-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_entrance',
            field=models.BooleanField(default=False),
        ),
    ]
