# Generated by Django 2.1.7 on 2019-07-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_escritorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritorio',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Escritorio'),
        ),
    ]
