# Generated by Django 2.1.7 on 2019-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_escritorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tema', models.CharField(max_length=255)),
                ('descricao_tema', models.TextField()),
                ('documentos', models.ManyToManyField(blank=True, to='conteudo.Files')),
                ('ementas', models.ManyToManyField(blank=True, to='conteudo.Ementas')),
            ],
        ),
        migrations.RemoveField(
            model_name='escritorio',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='escritorio',
            name='membros',
        ),
        migrations.DeleteModel(
            name='Escritorio',
        ),
    ]
