# Generated by Django 2.1.7 on 2019-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_auto_20190425_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temas',
        ),
        migrations.AddField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='d484bf341d974a7185ca', max_length=150, unique=True),
        ),
    ]
