# Generated by Django 2.1.7 on 2019-05-02 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudo', '0004_auto_20190425_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='2f3409d702caeaf5', max_length=150, unique=True),
        ),
    ]
