# Generated by Django 2.1.7 on 2019-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0005_auto_20190502_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='7b93d4683b3d6d8b', max_length=150, unique=True),
        ),
    ]
