# Generated by Django 2.1.7 on 2019-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0006_auto_20190516_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementas',
            name='orgao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='79c10aebd638c1d1', max_length=150, unique=True),
        ),
    ]
