# Generated by Django 2.1.7 on 2019-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0007_auto_20190517_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ementas',
            new_name='Ementa',
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='ementas',
            new_name='ementa',
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='fa77b49b367b4990', max_length=150, unique=True),
        ),
    ]
