# Generated by Django 2.1.7 on 2019-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0009_auto_20190520_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='2ce0ebd66bfc44b0', max_length=150, unique=True),
        ),
    ]
