# Generated by Django 2.1.7 on 2019-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0010_auto_20190520_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='data_sessao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='decisao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='materia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='numero_acordao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='relator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ementa',
            name='tipo_recurso',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='9c1441e8385d7875', max_length=150, unique=True),
        ),
    ]
