# Generated by Django 2.1.7 on 2019-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0011_auto_20190603_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='citacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='392da6f53c3b02d7', max_length=150, unique=True),
        ),
    ]
