# Generated by Django 2.1.7 on 2019-06-19 19:02

from django.db import migrations, models
import jurisintel.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0012_auto_20190603_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='identifier_code',
            field=models.CharField(default='30ce20b2159ad30d', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=jurisintel.storage_backends.ThumbnailStorage(), upload_to=''),
        ),
    ]
